### ISSUE TITLE
add an audio-only mode

### ISSUE THREAD

**Issue by maxlath** [aug-riedinger/NovaTube#5]
most of the time, I use it to have audio in the background and don't make use of the video, which nevertheless keeps eating my resources ;)
Isn't there some option in the youtube API to just get the audio?

**Comment by aug-riedinger** [comment]
That's exactly the opposite way: it is in youtube's TOS that the video **must** be displayed on the screen. Besides the resource issue (which consequently is really technically unsolvable), some music services might want to hide the video to make it look like their own music player but those services get their access to the API removed if they do so.

Regarding your performance issue, Novatube *is* based on Youtube, hence requires more or less the same amount of resource than there. If it is not the case, there might be some memory leak in the app and that's another issue, which should be tracked and solved for sure. As far as I am concerned, I haven't experienced any memory leak yet, thanks to the beautiful React library. :smile:

Sorry dude, not everything can be optimized as much as you'd wish! :smile: 

Finally, I always find it cool to have the video, even if I look at it only to skip a track or save one, sometimes I appreciate the video, and find it was worth looking at it.

**Comment by maxlath** [comment]
No worries, it's the same resource consumption as on youtube (and probably less given all the noise their ;) )
